### ISSUE TITLE
Prefix all routes

### ISSUE THREAD

**Issue by kralmichal** [contributte/api#21]
It would be nice to be able to set in config something like

```neon
api:
    prefix: /api/v1
```

and then `@RootPath("/foo")` would mean url `https://<host>/api/v1/foo`

**Comment by f3l1x** [comment]
It's similar with https://github.com/contributte/api/issues/20.

```php
/**
 * @Group(api/v1)
 */
abstract class ApiV1Controller {}
```

**Comment by f3l1x** [comment]
But, good point anyway, I'll try to resolve it with `BasePathMiddleware`. What about if you would like to handle `api/v1` and also `api/v2`, it can't be resolved via prefix, right?

**Comment by kralmichal** [comment]
Yes good point, prefix doesn't solves how to handle versioning.

**Comment by f3l1x** [comment]
@kralmichal We are working on it, just FYI.

**Comment by f3l1x** [comment]
It's implemented in here (apitte/core):

- https://github.com/apitte/core/blob/master/src/Annotation/Controller/GroupPath.php
- https://github.com/apitte/playground/blob/master/fullstack/app/controllers/BaseV1Controller.php#L8-L11
