### ISSUE TITLE
Generate docs from anotations

### ISSUE THREAD

**Issue by landsman** [contributte/api#26]
I am using this bundle for creating docs on Symfony:
https://symfony.com/doc/master/bundles/NelmioApiDocBundle/index.html

do you think that support for something like this could be possible?

**Comment by f3l1x** [comment]
Yep. :-) 

We're actually working on OpenApi specification, therefor you can use swagger-like generators. :-)

**Comment by f3l1x** [comment]
This project is going to be split to more repositories. 

Generated docs you can find here: https://github.com/apitte/openapi

<img width="845" alt="cursor_and_localhost_8000__debug__default" src="https://user-images.githubusercontent.com/538058/31266049-3b6b369a-aa72-11e7-89d0-7ebba026a335.png">
